---
  - name: Add PHP PPA repository
    become: true
    apt_repository: repo=ppa:ondrej/php
    register: installed_php_ppa

  - name: Update apt again
    become: true
    apt:  update_cache=yes
    when: installed_php_ppa.changed

  - name: Install PHP Libraries
    become: true
    apt:  package="{{ item }}" state=latest
    with_items:
     - php7.0-fpm
     - php7.0-cli
     - php7.0-gd
     - php7.0-curl
     - php7.0-zip         # Composer installs
     - php7.0-mysqlnd     # MySQL Native Driver (Doctrine)
     - php7.0-xml         # Unit Tests
     - php7.0-mbstring    # Codeception Tests
     - php7.0-intl        # Localization

  - name: Configure PHP FPM Pool
    template: src=fpmpool.j2 dest=/etc/php/7.0/fpm/pool.d/www.conf force=true
    notify: restart php-fpm

  - name: Configure php-fpm php.ini
    ini_file:
      dest: /etc/php/7.0/fpm/php.ini
      section: PHP
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { option: 'post_max_size',       value: "50M" }
      - { option: 'short_open_tag',      value: "On" }
      - { option: 'upload_max_filesize', value: "25M" }
    notify: restart php-fpm

  - name: Configure php-cli php.ini
    ini_file:
      dest: /etc/php/7.0/cli/php.ini
      section: PHP
      option: "{{ item.option }}"
      value: "{{ item.value }}"
    with_items:
      - { option: 'short_open_tag',      value: "On" }