---
  - name: Install nginx
    become: true
    apt:  pkg=nginx state=latest

  - name: Change default nginx site
    become: true
    template: src=default.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: Turn sendfile off on nginx for local development
    become: true
    replace:
      dest: /etc/nginx/nginx.conf
      regexp: 'sendfile on;'
      replace: 'sendfile off;'
    when: app_env == "development"